### PR TITLE
Search BLoC pattern without filter

### PR DESCRIPTION
**Pull request by marmot0814**

### CODE REVIEW

**Comment by marmot0814** [comment]
Should the pubspec.lock file need to be in the .gitignore file?

**Comment by anitaHey** [comment]
Yes I think we should put pubspec.lock to .gitignore😂 Or it will show conflicts every time.

**Comment by marmot0814** [comment]
Maybe I need some time to solve the conflict.

**Comment by marmot0814** [comment]
I solved the conflict.
Could everyone test it again in order to prevent that I delete your code or something get wrong.
Thx 
@anitaHey @jill880829

**Comment by jill880829** [comment]
The travel schedule page disappears. Is it normal?

**Comment by jill880829** [comment]
image
Is the "loading failed" message normal?

**Comment by anitaHey** [comment]
I can get the result here. Maybe you didn't press the button for search?
And we will add search suggestion next week, so that we can get something without pressing the search button😆

image

**Comment by jill880829** [comment]
I found the reason! It seems like I didn't enable the Places API. Besides this, what else API do I need to enable?

**Comment by anitaHey** [comment]
Just these two API😆

**Pull request merged**
